// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACt-a1QJQPoEtZbPpi8vtcziZnU3Lb7eE',
    appId: '1:504491579866:web:a1c7da141a9e99a876c8e3',
    messagingSenderId: '504491579866',
    projectId: 'fir-auth-email-9ddc0',
    authDomain: 'fir-auth-email-9ddc0.firebaseapp.com',
    storageBucket: 'fir-auth-email-9ddc0.appspot.com',
    measurementId: 'G-8TX7XH6WG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqm14daqKa_KYiOUFKOxAnU2ZtQEdhBdY',
    appId: '1:504491579866:android:6b80d6f72f6b731676c8e3',
    messagingSenderId: '504491579866',
    projectId: 'fir-auth-email-9ddc0',
    storageBucket: 'fir-auth-email-9ddc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUvZN5erRIecizvEheVQD2wccCcaQkNgk',
    appId: '1:504491579866:ios:f58a6282f0d50ca576c8e3',
    messagingSenderId: '504491579866',
    projectId: 'fir-auth-email-9ddc0',
    storageBucket: 'fir-auth-email-9ddc0.appspot.com',
    iosClientId: '504491579866-khp5sk9qf9i974ni0u0tpfi9v6movn2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUvZN5erRIecizvEheVQD2wccCcaQkNgk',
    appId: '1:504491579866:ios:f58a6282f0d50ca576c8e3',
    messagingSenderId: '504491579866',
    projectId: 'fir-auth-email-9ddc0',
    storageBucket: 'fir-auth-email-9ddc0.appspot.com',
    iosClientId: '504491579866-khp5sk9qf9i974ni0u0tpfi9v6movn2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
